# Schwarzschild black-hole immersed in an electric field
by Olivier Minazzoli and Maxime Wavasseur

The action of Entanled Relativiy reads as follows

<!-- $S = \int \mathrm{d}^4 x\sqrt{-g} \left( \frac{\Phi R}{2\kappa} + \sqrt{\Phi} \mathcal{L}_m \right)$ -->
$S = -\frac{1}{2}\int \mathrm{d}^4 x\sqrt{-g} \frac{\mathcal{L}_m^2}{R}$

The fields equations are

<!-- $G_{\mu\nu} = \frac{\kappa}{\sqrt{\Phi}}T_{\mu\nu} + \frac{1}{\Phi} \left( \nabla_\mu \nabla_\nu - g_{\mu\nu} \Box \right) \Phi$ -->
$G_{\mu\nu} = -\frac{R}{\mathcal{L}_m}T_{\mu\nu} + \frac{R^2}{\mathcal{L}_m^2} \left( \nabla_\mu \nabla_\nu - g_{\mu\nu} \Box \right) \frac{\mathcal{L}_m^2}{R^2}$,

and $\nabla_\sigma \left(\frac{\mathcal{L}}{R} F^{\mu \sigma}\right) = 0$,

with $\mathcal{L}_m = -\frac{1}{2} F_{\mu\nu}F^{\mu\nu}$.

The solution for the metric is
$$ds^2 = \Lambda^{\frac{28}{13}} \left[\left(1 - \frac{r_S}{r}\right)^{-1}dr^2 + r^2 d\theta^2 - \left(1 - \frac{r_S}{r}\right) dt^2 \right] + \Lambda^{-\frac{20}{13}} r^2 sin^2(\theta) d\varphi^2,$$
with
$$\Lambda = 1 + \frac{13}{48} E^2 r^2 sin^2(\theta).$$

The solution for the electromagnetic potential 4-vector is
$$A_t = E \left(1-\frac{r_S}{r} \right) r \cos \theta.$$

The solution is such that
$$-\frac{\mathcal{L}_m}{R} = \Lambda^{-2/13}.$$

Below, we verify that solution.

In [1]:
version()

'SageMath version 9.5, Release Date: 2022-01-30'

In [2]:
%display latex

In [3]:
from sage.manifolds.operators import dalembertian
from sage.manifolds.operators import laplacian
from sage.manifolds.operators import grad

In [4]:
M = Manifold(4, 'M', structure='Lorentzian')
print(M)

4-dimensional Lorentzian manifold M


/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
X.<t,r,th,ph> = M.chart(r"t r:(0,+oo) th:(0,pi):\theta ph:\varphi")
r_s = var('r_s')
assume(r_s>=0)
assume(r_s<r) # focus on exterior solution
E = var('E')

Let's define two functions to verify the properties of a null complex tetrad and to calculate the Weyl scalars.

In [6]:
def tetrad_cond(Ld,Nd,Md,Mbar_d):
    for c in [Ld,Nd,Md,Mbar_d]:
        if c.tensor_type() == (1, 0):
            raise ValueError("not a covariant vector")
    L, N, Mr, Mbar = Ld.up(g), Nd.up(g), Md.up(g), Mbar_d.up(g)

    l_scalar, n_scalar, m_scalar, mbar_scalar =  (Ld.contract(0, L, 0)).expr(), (Nd.contract(0, N, 0)).expr(),\
                                    (Md.contract(0, Mr, 0)).expr(), (Mbar_d.contract(0, Mbar, 0)).expr()
    lm, mn,ln, mbarm = (Ld.contract(0, Mr, 0)).expr(), (Nd.contract(0, Mr, 0)).expr(),\
                                    (Nd.contract(0, L, 0)).expr(), (Mbar_d.contract(0, Mr, 0)).expr()
    show(LatexExpr(r'l^{\mu}l_{\mu} = '),l_scalar, LatexExpr(r'\hspace{0.5cm} n^{\mu}n_{\mu} = '),\
         n_scalar, LatexExpr(r'\hspace{0.5cm} m^{\mu}m_{\mu} = '),m_scalar, \
         LatexExpr(r'\hspace{0.5cm} \bar{m}^{\mu}\bar{m}_{\mu} = '),mbar_scalar)

    show(LatexExpr(r'l^{\mu}m_{\mu} = '),lm, LatexExpr(r'\hspace{0.5cm} m^{\mu}n_{\mu} = '),\
         mn)
    
    show(LatexExpr(r'l^{\mu}n_{\mu} = '),ln, LatexExpr(r'\hspace{0.5cm} m^{\mu}\bar{m}_{\mu} = '),mbarm)

    g_t = M.tensor_field(0, 2, name='g_t')
    for i in range(4):
        g_t[i,i] = -2*Ld[i]*Nd[i] + 2*Md[i]*Mbar_d[i]
        g_t[i,i] = g_t[i,i].expr().canonicalize_radical().factor().factor()
    show(LatexExpr(r'g_{ab} = (l_{a}n_{b} +l_{b}n_{a} -m_{a}\bar{m}_{b}-m_{b}\bar{m}_{a}) \Rightarrow '), g_t - g == 0)

In [7]:
def Weyl_sc(K,L,Mb,MB,C):
    
    k, l, m, mb = K.up(g), L.up(g), Mb.up(g), MB.up(g)
    P0 = k*m*k*m
    P1 = k*l*k*m
    P2 = k*m*mb*l
    P3 = l*k*l*mb
    P4 = l*mb*l*mb

    l0 = r'\Psi_{0} = W_{\alpha\beta\gamma\delta}l^{\alpha}m^{\beta}l^{\gamma}m^{\delta} = ' 
    l1 = r'\Psi_{1} = W_{\alpha\beta\gamma\delta}l^{\alpha}n^{\beta}l^{\gamma}m^{\delta} = ' 
    l2 = r'\Psi_{2} = W_{\alpha\beta\gamma\delta}l^{\alpha}m^{\beta}\bar{m}^{\gamma}n^{\delta} = ' 
    l3 = r'\Psi_{3} = W_{\alpha\beta\gamma\delta}l^{\alpha}n^{\beta}\bar{m}^{\gamma}n^{\delta} = ' 
    l4 = r'\Psi_{4} = W_{\alpha\beta\gamma\delta}n^{\alpha}\bar{m}^{\beta}n^{\gamma}\bar{m}^{\delta} = ' 

    for (l,p) in zip([l0,l1,l2,l3,l4],[P0,P1,P2,P3,P4]):
        W_sc = C['_{abcd}']*p['^{abcd}']
        show(LatexExpr(l), W_sc.expr().canonicalize_radical().factor(), \
            LatexExpr(r' \underset{E = 0}{\longrightarrow}  '), W_sc.expr().subs(E=0).canonicalize_radical().factor())

# I. Definition of the fields

In [8]:
g = M.metric()
Lambda(r,th) = 1 + 13 / 48 * E**2 * (r*sin(th))**2

g[0,0] = -(1- r_s/r) * Lambda(r,th)**(28 / 13)
g[1,1] = 1/(1- r_s/r) * Lambda(r,th)**(28 / 13)
g[2,2] = r**2 * Lambda(r,th)**(28 / 13)
g[3,3] = (r*sin(th))**2 / Lambda(r,th)**(20 / 13)

pot_vec = M.tensor_field(0,1,name=r'A_{\mu}')
pot_vec[0]= E * (1 - r_s / r) * r * cos(th)
pot_vec[1]=0
pot_vec[2]=0
pot_vec[3]= 0

The metric and the potential vector read

In [9]:
show(g.display())
show(pot_vec.display())

g = (13/48*E^2*r^2*sin(th)^2 + 1)^(28/13)*(r_s/r - 1) dt⊗dt - (13/48*E^2*r^2*sin(th)^2 + 1)^(28/13)/(r_s/r - 1) dr⊗dr + (13/48*E^2*r^2*sin(th)^2 + 1)^(28/13)*r^2 dth⊗dth + r^2*sin(th)^2/(13/48*E^2*r^2*sin(th)^2 + 1)^(20/13) dph⊗dph

A_{\mu} = -E*r*(r_s/r - 1)*cos(th) dt

Let's define the covariant derivative

In [10]:
nab = g.connection() 

and the associated curvature quantities

In [11]:
Ric = g.ricci() #Ricci tensor
R = g.ricci_scalar() #Ricci scalar
G = Ric-R*g/2 #Einstein tensor

# II. Electromagnetic field equation

In [12]:
DF = nab(pot_vec) 

In [13]:
F=(DF['_ij']-DF['_ji'])._tensor
Fuu = F.up(g)
show(LatexExpr(r'F_{\mu\nu} ='), F.display())

F_{\mu\nu} = E*cos(th) dt⊗dr - (E*r - E*r_s)*sin(th) dt⊗dth - E*cos(th) dr⊗dt + (E*r - E*r_s)*sin(th) dth⊗dt

In [14]:
Lm = -F['_ij']*F.up(g)['^ij']/2
show(LatexExpr(r'L_{m} ='), Lm.expr().canonicalize_radical().factor())

L_{m} = -10616832*3^(4/13)*2^(3/13)*(r_s*sin(th)^2 - r)*E^2/((13*E^2*r^2*sin(th)^2 + 48)^(56/13)*r)

<!-- Let's verify the Maxwell equations $\triangledown\left(\sqrt{\phi}F_{\mu\nu}\right)=0$  -->
Let's verify the Maxwell equations $\nabla_\sigma \left(\frac{\mathcal{L}}{R} F^{\mu \sigma}\right) = 0$

In [15]:
N = nab(Lm / R *F.up(g))['_i^ij']
N == 0

True

In [16]:
E_elec = M.tensor_field(1,0)
for i in [1, 2, 3]:  
    E_elec[i] = F[0, i].factor()
show(LatexExpr(r'E^{\mu} = '),E_elec[:])

E^{\mu} =  [0, E*cos(th), -E*(r - r_s)*sin(th), 0]

## II.1. Properties

In [17]:
show(LatexExpr(r'L_{m}\Lambda^{56/13} ='), (Lm*Lambda**(56/13)).expr().canonicalize_radical().factor())
show(LatexExpr(r'\Rightarrow L_{m} = -\frac{{\left(r_{s} \sin\left({\theta}\right)^{2} - r\right)} E^{2}}{\Lambda^{56/13}r}'))
show(LatexExpr(r'\lim_{\theta \to 0} \Lambda(r,\theta) =1 \Rightarrow  \lim_{\theta \to 0} L_{m} = '), Lm.expr().subs(th=0).canonicalize_radical())

L_{m}\Lambda^{56/13} = -(r_s*sin(th)^2 - r)*E^2/r

\Rightarrow L_{m} = -\frac{{\left(r_{s} \sin\left({\theta}\right)^{2} - r\right)} E^{2}}{\Lambda^{56/13}r}

\lim_{\theta \to 0} \Lambda(r,\theta) =1 \Rightarrow  \lim_{\theta \to 0} L_{m} =  E^2

We can check that $\frac{10616832\times3^{4/13}\times2^{3/13}}{48^{56/13}}=1$

In [18]:
((10616832*3**(4/13)*2**(3/13)/ 48**(56/13)).canonicalize_radical() - 1).is_zero()

True

# III. The metric field equation

Let's define the stress-energy tensor $T_{\mu\nu}=2\left(F_{\rho\mu}F^{\rho}_{\hspace{0.2cm}\nu}-\frac{1}{4}g_{\mu\nu}F^{2}\right)$ 

In [19]:
T = 2*(F.up(g,1)['_i^j']*F['_kj'] + g*Lm/2)

In [20]:
T_scalar = g.inverse()['^ab'] * T['_ab']

In [21]:
T_scalar == 0

True

In [22]:
S = (nab(nab(Lm**2 / R**2 )) - g*(Lm**2 / R**2).dalembertian()) * R**2 / Lm**2 

And the field equation

In [23]:
G == - R / Lm * T + S

True

# IV. The scalar-field form $-\frac{\mathcal{L}_m}{R} = \Lambda^{-2/13}$

In [24]:
Lambda**(-2/13) + Lm/R == 0

True

## IV.1. Properties

In [25]:
show(LatexExpr(r'R ='), R.expr().canonicalize_radical().factor())
show(LatexExpr(r'R\Lambda^{54/13} ='), (R*Lambda**(54/13)).expr().canonicalize_radical().factor())
show(LatexExpr(r'\Rightarrow R = \frac{{\left(r_{s} \sin\left({\theta}\right)^{2} - r\right)} E^{2}}{\Lambda^{54/13}r} = L_{m} \Lambda^{2/13}'))
show(LatexExpr(r'\lim_{\theta \to 0} \Lambda(r,\theta) =1 \Rightarrow  \lim_{\theta \to 0} R = '), R.expr().subs(th=0).canonicalize_radical())

R = 5308416*3^(2/13)*2^(8/13)*(r_s*sin(th)^2 - r)*E^2/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*r)

R\Lambda^{54/13} = (r_s*sin(th)^2 - r)*E^2/r

\Rightarrow R = \frac{{\left(r_{s} \sin\left({\theta}\right)^{2} - r\right)} E^{2}}{\Lambda^{54/13}r} = L_{m} \Lambda^{2/13}

\lim_{\theta \to 0} \Lambda(r,\theta) =1 \Rightarrow  \lim_{\theta \to 0} R =  -E^2

We can check that $\frac{5308416\times3^{2/13}\times2^{8/13}}{48^{54/13}}=1$

In [26]:
((5308416*3**(2/13)*2**(8/13) / 48**(54/13)).canonicalize_radical() - 1).is_zero()

True

# V. Petrov classification

Let's first define the null tetrad components

In [27]:
C = (g.weyl()).down(g)

Let's first define the null tetrad components

In [28]:
K = M.one_form({X.frame(): [sqrt(-g[0,0]/2), sqrt(g[1,1]/2), 0, 0]})
L = M.one_form({X.frame(): [sqrt(-g[0,0]/2), -sqrt(g[1,1]/2), 0, 0]})
Mb = M.one_form({X.frame(): [0, 0, sqrt(g[2,2]/2), i*sqrt(g[3,3]/2)]})
MB = M.one_form({X.frame(): [0, 0, sqrt(g[2,2]/2), -i*sqrt(g[3,3]/2)]})

Now we check that the tetrad components satisfy the orthogonality and normalization conditions and are related to the metric.

In [29]:
tetrad_cond(K,L,Mb,MB)

l^{\mu}l_{\mu} =  0 \hspace{0.5cm} n^{\mu}n_{\mu} =  0 \hspace{0.5cm} m^{\mu}m_{\mu} =  5 \hspace{0.5cm} \bar{m}^{\mu}\bar{m}_{\mu} =  5

l^{\mu}m_{\mu} =  0 \hspace{0.5cm} m^{\mu}n_{\mu} =  0

l^{\mu}n_{\mu} =  -1 \hspace{0.5cm} m^{\mu}\bar{m}_{\mu} =  -4

g_{ab} = (l_{a}n_{b} +l_{b}n_{a} -m_{a}\bar{m}_{b}-m_{b}\bar{m}_{a}) \Rightarrow  False

In [30]:
Weyl_sc(K,L,Mb,MB,C)

\Psi_{0} = W_{\alpha\beta\gamma\delta}l^{\alpha}m^{\beta}l^{\gamma}m^{\delta} =  -110592*3^(2/13)*2^(8/13)*(35*E^2*r^2*sin(th)^2 - 144)*E^2*(r - r_s)*sin(th)^2/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*r)  \underset{E = 0}{\longrightarrow}   0

\Psi_{1} = W_{\alpha\beta\gamma\delta}l^{\alpha}n^{\beta}l^{\gamma}m^{\delta} =  27648*3^(2/13)*2^(8/13)*(35*E^2*r^2*sin(th)^2 - 144)*E^2*sqrt(r - r_s)*cos(th)*sin(th)/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*sqrt(r))  \underset{E = 0}{\longrightarrow}   0

\Psi_{2} = W_{\alpha\beta\gamma\delta}l^{\alpha}m^{\beta}\bar{m}^{\gamma}n^{\delta} =  4608*3^(2/13)*2^(8/13)*(840*E^4*r^5*sin(th)^4 - 423*E^4*r^4*r_s*sin(th)^4 - 560*E^4*r^5*sin(th)^2 - 3456*E^2*r^3*sin(th)^2 + 1248*E^2*r^2*r_s*sin(th)^2 + 2304*E^2*r^3 + 2304*r_s)/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*r^3)  \underset{E = 0}{\longrightarrow}   2*r_s/r^3

\Psi_{3} = W_{\alpha\beta\gamma\delta}l^{\alpha}n^{\beta}\bar{m}^{\gamma}n^{\delta} =  -27648*3^(2/13)*2^(8/13)*(35*E^2*r^2*sin(th)^2 - 144)*E^2*sqrt(r - r_s)*cos(th)*sin(th)/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*sqrt(r))  \underset{E = 0}{\longrightarrow}   0

\Psi_{4} = W_{\alpha\beta\gamma\delta}n^{\alpha}\bar{m}^{\beta}n^{\gamma}\bar{m}^{\delta} =  -110592*3^(2/13)*2^(8/13)*(35*E^2*r^2*sin(th)^2 - 144)*E^2*(r - r_s)*sin(th)^2/((13*E^2*r^2*sin(th)^2 + 48)^(54/13)*r)  \underset{E = 0}{\longrightarrow}   0

### Type D in the case E=0

## Kretschmann scalar

In [31]:
Rie = g.riemann()
Kr = Rie.down(g)['_{abcd}'] * Rie.up(g)['^{abcd}']
Kr.expr()

42467328*(25067520*3^(4/13)*2^(3/13)*E^4*r^6 - 3*(272272*3^(4/13)*2^(3/13)*E^8*r^9*r_s - 470369*3^(4/13)*2^(3/13)*E^8*r^8*r_s^2)*sin(th)^8 - 32*(208854*3^(4/13)*2^(3/13)*E^6*r^6*r_s^2 + 7*(7117*3^(4/13)*2^(3/13)*E^8*r^9 - 10872*3^(4/13)*2^(3/13)*E^6*r^7)*r_s)*sin(th)^6 + 31850496*3^(4/13)*2^(3/13)*E^2*r^3*r_s + 64*(16709*3^(4/13)*2^(3/13)*E^8*r^10 + 325512*3^(4/13)*2^(3/13)*E^4*r^4*r_s^2 + 24*(6559*3^(4/13)*2^(3/13)*E^6*r^7 + 4680*3^(4/13)*2^(3/13)*E^4*r^5)*r_s)*sin(th)^4 - 24576*(238*3^(4/13)*2^(3/13)*E^6*r^8 - 702*3^(4/13)*2^(3/13)*E^2*r^2*r_s^2 + 3*(745*3^(4/13)*2^(3/13)*E^4*r^5 + 648*3^(4/13)*2^(3/13)*E^2*r^3)*r_s)*sin(th)^2 + 15925248*3^(4/13)*2^(3/13)*r_s^2)/((815730721*E^16*r^22*sin(th)^16 + 24095430528*E^14*r^20*sin(th)^14 + 311387102208*E^12*r^18*sin(th)^12 + 2299473985536*E^10*r^16*sin(th)^10 + 10612956856320*E^8*r^14*sin(th)^8 + 31349041790976*E^6*r^12*sin(th)^6 + 57875154075648*E^4*r^10*sin(th)^4 + 61055107596288*E^2*r^8*sin(th)^2 + 28179280429056*r^6)*(13*E^2*r^2*sin(th)^2 + 48)^(4/13))

In [32]:
Kr.expr().subs(E=0).canonicalize_radical().factor()

12*r_s^2/r^6

In [33]:
Kr.expr().numerator().taylor(r, 0, 1).canonicalize_radical().factor()

676302730297344*3^(4/13)*2^(3/13)*r_s^2

In [34]:
Kr.expr().denominator().taylor(r, 0, 1).canonicalize_radical().factor()

0

### The Kretschmann scalar diverges at $r=0$ for all $\theta$.